# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
