# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20181207_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_words',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
